version: '3.9'

services:
  server:
    image: 'in-touch-backend:in-touch-backend-docker'
    ports:
      - 8080:8080
    build:
      context: ./src/server/
    container_name: in-touch-server
    volumes:
      - ./src/server/:/server/.
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/in-touch
      - SPRING_DATASOURCE_USERNAME=in-touch
      - SPRING_DATASOURCE_PASSWORD=in-touch
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:16'
    ports:
      - 5432:5432
    container_name: db
    environment:
      - POSTGRES_USER=in-touch
      - POSTGRES_PASSWORD=in-touch
