version: '2'

services:
  app: 
    image: 'in-touch:in-touch-docker'
    ports:
      - 8080:8080
    build: 
      context: .
    container_name: in-touch
    depends_on: 
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/in-touch
      - SPRING_DATASOURCE_USERNAME=in-touch
      - SPRING_DATASOURCE_PASSWORD=in-touch
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:16'
    container_name: db
    environment:
      - POSTGRES_USER=in-touch
      - POSTGRES_PASSWORD=in-touch